# E-Commerce Data Preprocessing & Quick Analysis

This notebook performs simple **data cleaning and basic analysis** on:

- Orders.csv
- Customers.csv
- Products.csv
- Categories.csv

The cleaned data can then be used for SQL EDA.

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
orders = pd.read_csv('./data/Orders.csv')
customers = pd.read_csv('./data/Customers.csv')
products = pd.read_csv('./data/Products.csv')
categories = pd.read_csv('./data/Categories.csv')

print('Orders:', orders.shape)
print('Customers:', customers.shape)
print('Products:', products.shape)
print('Categories:', categories.shape)

Orders: (51290, 18)
Customers: (38997, 4)
Products: (42, 3)
Categories: (5, 3)

In [7]:
print('Orders')
display(orders.head())

print('Customers')
display(customers.head())

print('Products')
display(products.head())

print('Categories')
display(categories.head())

Orders

,Order_Id,Order_Date,Time,Aging,Customer_Id,Gender,Device_Type,Customer_Login_type,Product,Product_Category,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Payment_Method,Product_Id
0,1,02-01-2018,10:56:33,8.0,37077,Female,Web,Member,Car Media Players,Auto & Accessories,140.0,1.0,0.3,46.0,4.6,Medium,credit_card,1
1,2,24-07-2018,20:41:37,2.0,59173,Female,Web,Member,Car Speakers,Auto & Accessories,211.0,1.0,0.3,112.0,11.2,Medium,credit_card,2
2,3,08-11-2018,8:38:49,8.0,41066,Female,Web,Member,Car Body Covers,Auto & Accessories,117.0,5.0,0.1,31.2,3.1,Critical,credit_card,3
3,4,18-04-2018,19:28:06,7.0,50741,Female,Web,Member,Car & Bike Care,Auto & Accessories,118.0,1.0,0.3,26.2,2.6,High,credit_card,4
4,5,13-08-2018,21:18:39,9.0,53639,Female,Web,Member,Tyre,Auto & Accessories,250.0,1.0,0.3,160.0,16.0,Critical,credit_card,5

Customers

   Customer_Id Gender Device_Type Customer_Login_type
0        10000   Male         Web              Member
1        10002   Male         Web              Member
2        10004   Male         Web               Guest
3        10006   Male         Web              Member
4        10013   Male         Web              Member

Products

   Product_Id       Product_Name    Product_Category
0           1  Car Media Players  Auto & Accessories
1           2       Car Speakers  Auto & Accessories
2           3    Car Body Covers  Auto & Accessories
3           4    Car & Bike Care  Auto & Accessories
4           5               Tyre  Auto & Accessories

Categories

   Category_Id       Category_Name  Parent_Category_Id
0            1         Electronics                 NaN
1            2  Auto & Accessories                 NaN
2            3  Mobile Accessories                 1.0
3            4     Car Accessories                 2.0
4            5    Bike Accessories                 2.0

In [8]:
# Check missing value
print(f"Orders Missing values: \n{orders.isnull().sum()}")

print(f"\nCustomers Missing values: \n{customers.isnull().sum()}")

print(f"\nProducts Missing values: \n{products.isnull().sum()}")

print(f"\nCategories Missing values: \n{categories.isnull().sum()}")

Orders Missing values:
Order_Id               0
Order_Date             0
Time                   0
Aging                  1
Customer_Id            0
Gender                 0
Device_Type            0
Customer_Login_type    0
Product                0
Product_Category       0
Sales                  1
Quantity               2
Discount               1
Profit                 0
Shipping_Cost          1
Order_Priority         2
Payment_Method         0
Product_Id             0
dtype: int64

Customers Missing values:
Customer_Id            0
Gender                 0
Device_Type            0
Customer_Login_type    0
dtype: int64

Products Missing values:
Product_Id          0
Product_Name        0
Product_Category    0
dtype: int64

Categories Missing values:
Category_Id           0
Category_Name         0
Parent_Category_Id    2
dtype: int64

In [9]:
# Filling Null Values.
orders['Aging'] = orders['Aging'].fillna(orders['Aging'].median())
orders['Sales'] = orders['Sales'].fillna(orders['Sales'].median())
orders['Quantity'] = orders['Quantity'].fillna(orders['Quantity'].median())
orders['Discount'] = orders['Discount'].fillna(orders['Discount'].median())
orders['Shipping_Cost'] = orders['Shipping_Cost'].fillna(orders['Shipping_Cost'].median())
orders['Order_Priority'] = orders['Order_Priority'].fillna(
    orders['Order_Priority'].mode()[0]
)

Parent_Category_Id should be as NULL/NaN, because that preserves the original hierarchy information.

In [10]:
# Check duplicate rows
print('Orders duplicates:', orders.duplicated().sum())
print('Customers duplicates:', customers.duplicated().sum())
print('Products duplicates:', products.duplicated().sum())
print('Categories duplicates:', categories.duplicated().sum())
# If present remove them using .drop_duplicates() methods

Orders duplicates: 0
Customers duplicates: 0
Products duplicates: 0
Categories duplicates: 0

In [11]:
# Remove unnecessary spaces from important text fields.
orders['Gender'] = orders['Gender'].str.strip()
orders['Device_Type'] = orders['Device_Type'].str.strip()
orders['Customer_Login_type'] = orders['Customer_Login_type'].str.strip()
orders['Product'] = orders['Product'].str.strip()
orders['Product_Category'] = orders['Product_Category'].str.strip()
orders['Order_Priority'] = orders['Order_Priority'].str.strip()
orders['Payment_Method'] = orders['Payment_Method'].str.strip()

customers['Gender'] = customers['Gender'].str.strip()
customers['Device_Type'] = customers['Device_Type'].str.strip()
customers['Customer_Login_type'] = customers['Customer_Login_type'].str.strip()

products['Product_Name'] = products['Product_Name'].str.strip()
products['Product_Category'] = products['Product_Category'].str.strip()

categories['Category_Name'] = categories['Category_Name'].str.strip()

print('Text cleaning completed.')

Text cleaning completed.

In [12]:
# Convert the order date into a proper date and important numeric columns into numeric types.

orders['Order_Date'] = pd.to_datetime(orders['Order_Date'] , dayfirst=True , errors='coerce')
orders['Sales'] = pd.to_numeric(orders['Sales'], errors='coerce')
orders['Quantity'] = pd.to_numeric(orders['Quantity'], errors='coerce')
orders['Discount'] = pd.to_numeric(orders['Discount'], errors='coerce')
orders['Profit'] = pd.to_numeric(orders['Profit'], errors='coerce')
orders['Shipping_Cost'] = pd.to_numeric(orders['Shipping_Cost'], errors='coerce')
orders['Aging'] = pd.to_numeric(orders['Aging'], errors='coerce')

print(orders[['Order_Date', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping_Cost']].dtypes)

Order_Date       datetime64[ns]
Sales                   float64
Quantity                float64
Discount                float64
Profit                  float64
Shipping_Cost           float64
dtype: object

In [13]:
# Checking for negative Values
print('Negative Quantity:', (orders['Quantity'] < 0).sum())
print('Negative Sales:', (orders['Sales'] < 0).sum())
print('Negative Discount:', (orders['Discount'] < 0).sum())
print('Negative Shipping Cost:', (orders['Shipping_Cost'] < 0).sum())
print('Negative Profit:', (orders['Profit'] < 0).sum())

Negative Quantity: 0
Negative Sales: 0
Negative Discount: 0
Negative Shipping Cost: 0
Negative Profit: 0

In [14]:
orders.to_csv('Orders.csv', index=False)
customers.to_csv('Customers.csv', index=False)
products.to_csv('Products.csv', index=False)
categories.to_csv('Categories.csv', index=False)

print('CSV files saved successfully.')

CSV files saved successfully.

In [ ]:
from pathlib import Path
import sqlite3

db_path = Path("Ecommerce_SQL_DATAProject1.db")
conn = sqlite3.connect(db_path)

orders.to_sql("orders", conn, if_exists="replace", index=False)
customers.to_sql("customers", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
categories.to_sql("categories", conn, if_exists="replace", index=False)



conn.close()
print("Created:", db_path)

Created: Ecommerce_SQL_DATAProject1.db